### ISSUE TITLE
Hard Coded API version segment

### ISSUE THREAD

**Issue by marioSantos97** [iamBiB/api-versioning-fallback#1]
Hello, i am trying to use this in my lumen application, i noticed a hardcoded line which is giving me some problems. 
In ApiVersioningFallback.php, line 34, its assumed that the api version will come in the index 0 of the $segments array, but that might not be the case every time, in my case it comes in the index number 1, so this line should be replaced by something more dinamic, like a regex for example, that you could even configure in the api-versioning.php file so it could be fully editable.

Thanks for developing this package, its helping me a lot!
Kind Regards, 

M+ario

**Comment by iamBiB** [comment]
Thanks for the feedback. Added the segment_no in config file
